from asyncio import Task
from collections.abc import Coroutine
from typing import TypeVar, Any

T = TypeVar("T")

class TaskGroup:
    async def __aenter__(self) -> TaskGroup: ...
    async def __aexit__(self, _: Any, __: Any, ___: Any) -> None: ...
    def create_task(
        self, coro: Coroutine[Any, Any, T], *, name: str | None = ...
    ) -> Task[T]: ...
